export const SEARCH_REQUEST = "SEARCH_REQUEST";
export const SEARCH_ERROR = "SEARCH_ERROR";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_RESET = "SEARCH_RESET";

export const SET_SEARCH_INPUT = "SET_SEARCH_INPUT";

export const SET_SEARCH_REFERENCE = "SET_SEARCH_REFERENCE";
