export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const SET_AUTOPLAY = "SET_AUTOPLAY";
export const NEXT_SONG = "NEXT_SONG";
export const PREVIOUS_SONG = "PREVIOUS_SONG";

export const SET_PREQUEUE = "SET_PREQUEUE";
export const SET_QUEUE_AND_CURRENT_SONG = "SET_QUEUE_AND_CURRENT_SONG";
export const SET_QUEUE = "SET_QUEUE";
export const SET_SHUFFLE = "SET_SHUFFLE";
export const ADD_SONG_TO_PREQUEUE = "ADD_SONG_TO_PREQUEUE";

export const DELETE_SONG_FROM_QUEUE = "DELETE_SONG_FROM_QUEUE";
export const IS_CURRENT_SONG_DELETED_RESET = "IS_CURRENT_SONG_DELETED_RESET";

export const UPDATE_SONG_FROM_QUEUE = "UPDATE_SONG_FROM_QUEUE";

export const SET_LAST_SONG_PLAYED = "SET_LAST_SONG_PLAYED";
