export const SET_CURRENT_SONG = "SET_CURRENT_SONG";
export const SET_AUTOPLAY = "SET_AUTOPLAY";
export const NEXT_SONG = "NEXT_SONG";
export const PREVIOUS_SONG = "PREVIOUS_SONG";

export const SET_PREQUEUE = "SET_PREQUEUE";
export const SET_QUEUE_AND_CURRENT_SONG = "SET_QUEUE_AND_CURRENT_SONG";
export const SET_QUEUE = "SET_QUEUE";
export const SET_SHUFFLE = "SET_SHUFFLE";
