export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const SET_USER = "SET_USER";

export const SET_FAVORITES_SUCCESS = "SET_FAVORITES_SUCCESS";
export const SET_FAVORITES_ERROR = "SET_FAVORITES_ERROR";
export const SET_FAVORITES_REQUEST = "SET_FAVORITES_REQUEST";
