export const EDIT_USER_REQUEST = "EDIT_USER_REQUEST";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";

export const SET_USER = "SET_USER";

export const SET_FAVORITES_SUCCESS = "SET_FAVORITES_SUCCESS";
export const SET_FAVORITES_ERROR = "SET_FAVORITES_ERROR";
export const SET_FAVORITES_REQUEST = "SET_FAVORITES_REQUEST";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_ERROR = "LIKE_ERROR";
export const LIKE_REQUEST = "LIKE_REQUEST";

export const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";
export const DISLIKE_ERROR = "DISLIKE_ERROR";
export const DISLIKE_REQUEST = "DISLIKE_REQUEST";
