export const CREATE_PLAYLIST_REQUEST = "CREATE_PLAYLIST_REQUEST";
export const CREATE_PLAYLIST_ERROR = "CREATE_PLAYLIST_ERROR";
export const CREATE_PLAYLIST_SUCCESS = "CREATE_PLAYLIST_SUCCESS";
export const CREATE_PLAYLIST_RESET = "CREATE_PLAYLIST_RESET";

export const PLAYLIST_RESET = "PLAYLIST_RESET";
