export const EDIT_SONG_SUCCESS = "EDIT_SONG_SUCCESS";
export const EDIT_SONG_ERROR = "EDIT_SONG_ERROR";
export const EDIT_SONG_REQUEST = "EDIT_SONG_REQUEST";

export const SET_FAVORITES_SUCCESS = "SET_FAVORITES_SUCCESS";
export const SET_FAVORITES_ERROR = "SET_FAVORITES_ERROR";
export const SET_FAVORITES_REQUEST = "SET_FAVORITES_REQUEST";

export const LIKE_SUCCESS = "LIKE_SUCCESS";
export const LIKE_ERROR = "LIKE_ERROR";
export const LIKE_REQUEST = "LIKE_REQUEST";

export const DISLIKE_SUCCESS = "DISLIKE_SUCCESS";
export const DISLIKE_ERROR = "DISLIKE_ERROR";
export const DISLIKE_REQUEST = "DISLIKE_REQUEST";

export const GET_MYSONGS_SUCCESS = "GET_MYSONGS_SUCCESS";
export const GET_MYSONGS_ERROR = "GET_MYSONGS_ERROR";
export const GET_MYSONGS_REQUEST = "GET_MYSONGS_REQUEST";

export const UPLOAD_SONG_REQUEST = "UPLOAD_SONG_REQUEST";
export const UPLOAD_SONG_ERROR = "UPLOAD_SONG_ERROR";
export const UPLOAD_SONG_SUCCESS = "UPLOAD_SONG_SUCCESS";
export const UPLOAD_SONG_RESET = "UPLOAD_SONG_RESET";
